In [4]:
# This is added to overcome python 3.7 json encoder warnings. Not required for the Demo
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Import NDArray -> N Dimensional Array -> A Data Container -> A Tensor Data Container
import mxnet as mx
from mxnet import nd

# Do Seed so that results are reproducible when using random initialization
mx.random.seed(1)

In [6]:
# SCALARS -> Just one value

# Initialize
scalar1 = nd.array([3])
scalar2 = nd.array([2])

print(scalar1)
# Addition
print('scalar1 + scalar2 = ', scalar1 + scalar2)

# Multiplication
print('scalar1 * scalar2 = ', scalar1 * scalar2)

# Division
print('scalar1 / scalar2 = ', scalar1 / scalar2)

# Power
print('scalar1 ** scalar2 = ', nd.power(scalar1,scalar2))


[ 3.]
<NDArray 1 @cpu(0)>
scalar1 + scalar2 =  
[ 5.]
<NDArray 1 @cpu(0)>
scalar1 * scalar2 =  
[ 6.]
<NDArray 1 @cpu(0)>
scalar1 / scalar2 =  
[ 1.5]
<NDArray 1 @cpu(0)>
scalar1 ** scalar2 =  
[ 9.]
<NDArray 1 @cpu(0)>


In [7]:
# Extract the scalar value from NDArray
scalar1.asscalar()

3.0

In [8]:
# VECTORS -> LIST OF VALUES -> 1 DIMENSIONAL

vector1 = nd.array([1, 2, 3, 4])
vector2 = nd.array([2, 4, 8, 10])

# Shape and Dimensions
print('vector1 shape - ', vector1.shape)
print('vector2 dimension - ', vector1.ndim)


matrix = nd.array([
                    [1],[2],[3],[4]
                  ])
print(matrix.shape)
print(matrix.ndim)

vector1 shape -  (4,)
vector2 dimension -  1
(4, 1)
2


In [9]:
# VECTOR - VECTOR operations

# Addition
print('vector1 + scalar2 = ', vector1 + vector2)

# Multiplication
print('vector1 * scalar2 = ', vector1 * vector2)

# Division
print('vector1 / scalar2 = ', vector1 / vector2)

vector1 + scalar2 =  
[  3.   6.  11.  14.]
<NDArray 4 @cpu(0)>
vector1 * scalar2 =  
[  2.   8.  24.  40.]
<NDArray 4 @cpu(0)>
vector1 / scalar2 =  
[ 0.5         0.5         0.375       0.40000001]
<NDArray 4 @cpu(0)>


In [10]:
# VECTOR - SCALAR Operations

scalar3 = 2

print('vector1 - ', vector1)
print('scalar3 - ', scalar3)

# Addition
print('vector1 + scalar3 = ', vector1 + scalar3)

# Multiplication
print('vector1 * scalar3 = ', vector1 * scalar3)

# Division
print('vector1 / scalar3 = ', vector1 / scalar3)


vector1 -  
[ 1.  2.  3.  4.]
<NDArray 4 @cpu(0)>
scalar3 -  2
vector1 + scalar3 =  
[ 3.  4.  5.  6.]
<NDArray 4 @cpu(0)>
vector1 * scalar3 =  
[ 2.  4.  6.  8.]
<NDArray 4 @cpu(0)>
vector1 / scalar3 =  
[ 0.5  1.   1.5  2. ]
<NDArray 4 @cpu(0)>


In [11]:
# MATRIX - LIST OF LIST OF VALUES - 2 DIMENSIONAL

matrix1 = nd.array([
    [1,2,3,4],
    [2,4,6,8]
])

matrix2 = nd.array([
                    [1,1,1,1],
                    [1,1,1,1]
                 ])


print('matrix1 = ', matrix1)
print('matrix2 = ', matrix2)

# SHAPE and DIMENSION (AXIS)
print('Shape of matrix = ', matrix1.shape)
print('Dimensions of matrix = ',matrix1.ndim)

matrix1 =  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>
matrix2 =  
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 2x4 @cpu(0)>
Shape of matrix =  (2, 4)
Dimensions of matrix =  2


In [12]:
# MATRIX - MATRIX OPERATIONS  (Since Tensors are of same shape - Elementwise operations )

# Addition
print('matrix1 + matrix2 = ', matrix1 + matrix2)

# Multiplication
print('matrix1 * matrix2 = ', matrix1 * matrix2)

# Division
print('matrix1 / matrix2 = ', matrix1 / matrix2)


matrix1 + matrix2 =  
[[ 2.  3.  4.  5.]
 [ 3.  5.  7.  9.]]
<NDArray 2x4 @cpu(0)>
matrix1 * matrix2 =  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>
matrix1 / matrix2 =  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>


In [13]:
# MATRIX - SCALAR OPERATIONS
scalar4 = 2

print('matrix1 - ', matrix1)
print('scalar4 - ', scalar4)

# Addition
print('matrix1 + scalar4 = ', matrix1 + scalar4)

# Multiplication
print('matrix1 * scalar4 = ', matrix1 * scalar4)

# Division
print('matrix1 / scalar4 = ', matrix1 / scalar4)

matrix1 -  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>
scalar4 -  2
matrix1 + scalar4 =  
[[  3.   4.   5.   6.]
 [  4.   6.   8.  10.]]
<NDArray 2x4 @cpu(0)>
matrix1 * scalar4 =  
[[  2.   4.   6.   8.]
 [  4.   8.  12.  16.]]
<NDArray 2x4 @cpu(0)>
matrix1 / scalar4 =  
[[ 0.5  1.   1.5  2. ]
 [ 1.   2.   3.   4. ]]
<NDArray 2x4 @cpu(0)>


In [14]:
# MATRIX - VECTOR OPERATIONS (REMEMBER BROADCASTING?)
vector3 = nd.array([1, 2, 3, 4])

print('matrix1 - ', matrix1)
print('vector3 - ', vector3)

# Addition
print('matrix1 + vector3 = ', matrix1 + vector3)

# Multiplication
print('matrix1 * vector3 = ', matrix1 * vector3)

# Division
print('matrix1 / vector3 = ', matrix1 / vector3)

matrix1 -  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>
vector3 -  
[ 1.  2.  3.  4.]
<NDArray 4 @cpu(0)>
matrix1 + vector3 =  
[[  2.   4.   6.   8.]
 [  3.   6.   9.  12.]]
<NDArray 2x4 @cpu(0)>
matrix1 * vector3 =  
[[  1.   4.   9.  16.]
 [  2.   8.  18.  32.]]
<NDArray 2x4 @cpu(0)>
matrix1 / vector3 =  
[[ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]]
<NDArray 2x4 @cpu(0)>


In [15]:
# DOT PRODUCTS, TRANSPOSE OF A TENSOR

matrix1 = nd.array([
                    [1,2,3,4],
                    [2,4,6,8]
                 ])

matrix2 = nd.array([
                    [1,1,1,1],
                    [1,1,1,1]
                 ])

print('matrix1 = ', matrix1)
print('matrix2 = ', matrix2)

# SHAPE and DIMENSION (AXIS)
print('Shape of matrix = ', matrix1.shape)
print('Dimensions of matrix = ',matrix1.ndim)

# DOT PRODUCT (4X2 dot 2X4) => (4X4)
dot_product = nd.dot(matrix1.T, matrix2)
print('dot_product = ', dot_product)

# SHAPE and DIMENSION (AXIS)
print('Shape of dot_product = ', dot_product.shape)
print('Dimensions of dot_product = ',dot_product.ndim)

matrix1 =  
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]]
<NDArray 2x4 @cpu(0)>
matrix2 =  
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 2x4 @cpu(0)>
Shape of matrix =  (2, 4)
Dimensions of matrix =  2
dot_product =  
[[  3.   3.   3.   3.]
 [  6.   6.   6.   6.]
 [  9.   9.   9.   9.]
 [ 12.  12.  12.  12.]]
<NDArray 4x4 @cpu(0)>
Shape of dot_product =  (4, 4)
Dimensions of dot_product =  2


In [16]:
# SOME COMMONLY USED USEFUL OPERATIONS

# Arange
arange_vector = nd.arange(10)
print('arange_vector - ', arange_vector)

# Reshape
arange_vector_to_matrix = arange_vector.reshape((5,2))
print('arange_vector_to_matrix - ', arange_vector_to_matrix)
                                                
# Sum of values of the Tensor
print(nd.sum(arange_vector_to_matrix))

# ABS
negative_tensor = nd.array([-1, -2, -3, 5])
print('Negative tensor - ', negative_tensor)
print('Abs of Negative tensor - ', nd.abs(negative_tensor))

arange_vector -  
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
<NDArray 10 @cpu(0)>
arange_vector_to_matrix -  
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]
<NDArray 5x2 @cpu(0)>

[ 45.]
<NDArray 1 @cpu(0)>
Negative tensor -  
[-1. -2. -3.  5.]
<NDArray 4 @cpu(0)>
Abs of Negative tensor -  
[ 1.  2.  3.  5.]
<NDArray 4 @cpu(0)>


In [17]:
# NORMS - L1 AND L2

# L1 Norm - Sum of absolute values of a Tensor
matrix5 = nd.array([
                    [-1, -2, -3, -4],
                    [1, 2, 3, 4]
                  ])

l1_norm = nd.sum(nd.abs(matrix5))

print('matrix5 - ', matrix5)
print('L1 norm - ', l1_norm)


# L2 Norm - Square root of Sum of squared values of a Tensor

l2_norm = nd.sqrt(nd.sum(nd.square(nd.abs(matrix5))))
print('L2 norm by hand - ', l2_norm)

# Or use built in MXNet L2 Norm function
print('L2 norm from MXNet - ', nd.norm(matrix5))

matrix5 -  
[[-1. -2. -3. -4.]
 [ 1.  2.  3.  4.]]
<NDArray 2x4 @cpu(0)>
L1 norm -  
[ 20.]
<NDArray 1 @cpu(0)>
L2 norm by hand -  
[ 7.74596691]
<NDArray 1 @cpu(0)>
L2 norm from MXNet -  
[ 7.74596691]
<NDArray 1 @cpu(0)>


In [18]:
# 5 DIMENSIONAL TENSOR

five_d_tensor = nd.array([
    [
        [
            [
                [1,2,3],
                [4,5,6]
            ]
        ]
    ]
])

In [19]:
five_d_tensor.ndim

5

In [20]:
five_d_tensor.shape

(1, 1, 1, 2, 3)