In [46]:
import numpy as np
import sys

In [47]:
np.random.normal(0.0, 2 ** -0.5, (2, 3))

array([[ 0.52381912,  1.26680442,  0.40520172],
       [-0.87759995, -0.80685654,  0.92894857]])

In [48]:
class PartyNN(object):
    
    def __init__(self, learning_rate=0.1):
        self.weights_0_1 = np.random.normal(0.0, 2 ** -0.5, (2, 3))
        self.weights_1_2 = np.random.normal(0.0, 1, (1, 2))
        self.sigmoid_mapper = np.vectorize(self.sigmoid)
        self.learning_rate = np.array([learning_rate])
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def predict(self, inputs):
        inputs_1 = np.dot(self.weights_0_1, inputs)
        outputs_1 = self.sigmoid_mapper(inputs_1)
        
        inputs_2 = np.dot(self.weights_1_2, outputs_1)
        outputs_2 = self.sigmoid_mapper(inputs_2)
        return outputs_2
    
    def train(self, inputs, expected_predict):     
        inputs_1 = np.dot(self.weights_0_1, inputs)
        outputs_1 = self.sigmoid_mapper(inputs_1)
        
        inputs_2 = np.dot(self.weights_1_2, outputs_1)
        outputs_2 = self.sigmoid_mapper(inputs_2)
        actual_predict = outputs_2[0]
        
        error_layer_2 = np.array([actual_predict - expected_predict])
        gradient_layer_2 = actual_predict * (1 - actual_predict)
        weights_delta_layer_2 = error_layer_2 * gradient_layer_2  
        self.weights_1_2 -= (np.dot(weights_delta_layer_2, outputs_1.reshape(1, len(outputs_1)))) * self.learning_rate
        
        error_layer_1 = weights_delta_layer_2 * self.weights_1_2
        gradient_layer_1 = outputs_1 * (1 - outputs_1)
        weights_delta_layer_1 = error_layer_1 * gradient_layer_1
        self.weights_0_1 -= np.dot(inputs.reshape(len(inputs), 1), weights_delta_layer_1).T  * self.learning_rate

In [34]:
def MSE(y, Y):
    return np.mean((y-Y)**2)

In [37]:
train = [
    ([0, 0, 0], 0),
    ([0, 0, 1], 1),
    ([0, 1, 0], 0),
    ([0, 1, 1], 0),
    ([1, 0, 0], 1),
    ([1, 0, 1], 1),
    ([1, 1, 0], 0),
    ([1, 1, 1], 0),
]

In [58]:
epochs = 200
learning_rate = 0.9

network = PartyNN(learning_rate=learning_rate)

for e in range(epochs):
    inputs_ = []
    correct_predictions = []
    for input_stat, correct_predict in train:
        network.train(np.array(input_stat), correct_predict)
        inputs_.append(np.array(input_stat))
        correct_predictions.append(np.array(correct_predict))
    
    train_loss = MSE(network.predict(np.array(inputs_).T), np.array(correct_predictions))
    sys.stdout.write("\rProgress: {}, Training loss: {}".format(str(100 * e/float(epochs))[:4], str(train_loss)[:5]))

Progress: 99.5, Training loss: 0.006

In [56]:
for input_stat, correct_predict in train:
    print("For input: {} the prediction is: {}, expected: {}".format(
        str(input_stat), 
        str(network.predict(np.array(input_stat)) > .5),
        str(correct_predict == 1)))

For input: [0, 0, 0] the prediction is: [False], expected: False
For input: [0, 0, 1] the prediction is: [ True], expected: True
For input: [0, 1, 0] the prediction is: [False], expected: False
For input: [0, 1, 1] the prediction is: [False], expected: False
For input: [1, 0, 0] the prediction is: [ True], expected: True
For input: [1, 0, 1] the prediction is: [ True], expected: True
For input: [1, 1, 0] the prediction is: [False], expected: False
For input: [1, 1, 1] the prediction is: [False], expected: False


In [57]:
for input_stat, correct_predict in train:
    print("For input: {} the prediction is: {}, expected: {}".format(
        str(input_stat), 
        str(network.predict(np.array(input_stat))),
        str(correct_predict == 1)))

For input: [0, 0, 0] the prediction is: [ 0.01847622], expected: False
For input: [0, 0, 1] the prediction is: [ 0.98929227], expected: True
For input: [0, 1, 0] the prediction is: [  1.48344783e-06], expected: False
For input: [0, 1, 1] the prediction is: [  3.56118537e-06], expected: False
For input: [1, 0, 0] the prediction is: [ 0.9893139], expected: True
For input: [1, 0, 1] the prediction is: [ 0.99585364], expected: True
For input: [1, 1, 0] the prediction is: [  3.60905164e-06], expected: False
For input: [1, 1, 1] the prediction is: [ 0.00398973], expected: False


In [59]:
network.weights_0_1

array([[ 1.58790794, -2.12925531,  1.59776326],
       [-2.03230383,  5.32610869, -2.03421187]])

In [60]:
network.weights_1_2

array([[ 3.58907674, -6.91668929]])